### ISSUE TITLE
Missing a7ExtensionMethods dependency?

### ISSUE THREAD

**Issue by johnlyn763** [alekkowalczyk/a7DocumentDbStudio#1]
Is there an assembly missing? When I try to build, I get lots of "type or namespace not found" for "a7ExtensionMethods". Thanks.

**Comment by alekkowalczyk** [comment]
I just commited a fix by adding the references assembly to this repository. The assemblies codes can be found in my repositories as well.
Please let me know if it fixed your issue.

**Comment by johnlyn763** [comment]
Yes, this fixed issue, thanks
