### ISSUE TITLE
Cannot start application

### ISSUE THREAD

**Issue by ChananPublic** [alekkowalczyk/a7DocumentDbStudio#2]
I can no longer run the application. At startup I get a popup saying "Cannot start application", "Application download did not succeed. Check your network connection, or contact your system administrator or network service provider"

There is nothing wrong with my connection. A friend of mine confirms the same issue.

I attached the log file

[Q8I0DBQI.log](https://github.com/alekkowalczyk/a7DocumentDbStudio/files/2598444/Q8I0DBQI.log)

**Comment by alekkowalczyk** [comment]
Hi!

It should be fixed now, thanks for the issue report.

**Comment by ChananPublic** [comment]
Thanks for the quick fix, it's working now
